version: "2"

services:
  nexus:
    restart: always
    image: sonatype/nexus3:3.34.1
    volumes:
      - "nexus-data:/nexus-data"
    ports:
      - "8081:8081"
      - "8082:8082"  
      - "8083:8083"
volumes:
  nexus-data: {}
